apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mern-frontend.fullname" . }}-nginx
  labels:
    {{- include "mern-frontend.labels" . | nindent 4 }}
data:
  default.conf: |
    upstream backend_upstream {
      server {{ .Values.backend.host }}:{{ .Values.backend.port }};
    }

    server {
      listen 80;

      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
      }

      # Proxy /api -> backend
      location /api/ {
        proxy_pass http://backend_upstream;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
